[build-system]
requires = ["setuptools>=77", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "nistchempy"
authors = [
    {name = "Ivan Yu. Chernyshov", email = "ivan.chernyshoff@gmail.com"}
]
maintainers = [
    {name = "Ivan Yu. Chernyshov", email = "ivan.chernyshoff@gmail.com"}
]
description = "Unofficial Python tools for querying NIST Chemistry WebBook pages and extracting molecular-property records"
readme = {file = "README.md", content-type = "text/markdown"}
license = "MIT"
license-files = ["LICENSE.md"]
keywords = [
    "NIST Chemistry WebBook",
    "chemical data",
    "molecular properties",
    "spectral data",
    "mass spectra",
    "infrared spectra",
    "gas chromatography",
    "cheminformatics",
    "scientific Python",
    "physical chemistry",
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Programming Language :: Python :: 3 :: Only",
    "Operating System :: OS Independent",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering",
    "Topic :: Scientific/Engineering :: Chemistry",
]
dependencies = [
  "requests",
  "pandas",
  "beautifulsoup4",
  "platformdirs"
]
requires-python = ">= 3.9"
dynamic = ["version"]

[project.optional-dependencies]
docs = [
  "sphinx",
  "sphinx-gallery",
  "sphinx-rtd-theme",
  "notebook",
  "nbconvert",
  "nbsphinx",
]
dev = [
  "build",
  "pytest",
  "coverage[toml]",
  "sphinx",
  "sphinx-gallery",
  "sphinx-rtd-theme",
  "notebook",
  "nbconvert",
  "nbsphinx",
]
structure = [
  "rdkit",
]

[project.urls]
Documentation = "https://mucommons.github.io/NistChemPy/"
Repository = "https://github.com/muCommons/NistChemPy.git"
Issues = "https://github.com/muCommons/NistChemPy/issues"

[project.scripts]
nistchempy = "nistchempy.cli:main"

[tool.setuptools.dynamic]
version = {attr = "nistchempy.__version__"}


